logging:
  config: classpath:logback.xml
server:
  port: 8782
xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
      executor:
        address: ''
        appname: xxl-job-executor-sample
        ip: ''
        logpath: /data/applogs/xxl-job/jobhandler
        logretentiondays: 30
        port: 9999