# management endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      # 给所有人显示 数据库，磁盘，ping等信息 https://www.jianshu.com/p/1aadc4c85f51
      show-details: always
  health:
    mail:
      enabled: false
#  server:
#    base-path: /actuator 会导致 管理路径冗余而失败 /actuator/actuator/info，不要添加这个
  info:
    java:
      enabled: true
    env:
      enabled: true # 先设置这里，才会显示info 信息 https://docs.spring.io/spring-boot/docs/2.7.7/reference/html/actuator.html#actuator.endpoints.info.custom-application-information
    os:
      enabled: true

mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
server:
  port: 8780
  servlet:
    context-path: /xxl-job-admin

eureka:
  instance:
    ip-address: 10.147.17.90
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.147.17.14:8761/eureka/,http://10.147.17.14:8762/eureka/

spring:
  application:
    name: xxl-job-admin
    cloud:
      inetutils:
        preferred-networks:
          - 10.147.17.*
        ignored-interfaces:
          - docker0
          - veth*
          - Vmware*
          - 10.9.2.65
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
      maximum-pool-size: 5
      minimum-idle: 1
      pool-name: HikariCP
      validation-timeout: 1000
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mail:
    from: xxx@163.com
    host: smtp.163.com
    password: 你的smtp授权密码
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
    username: xxx@163.com
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

xxl:
  job:
    accessToken: default_token
    i18n: zh_CN
    logretentiondays: 10
    triggerpool:
      fast:
        max: 10
      slow:
        max: 5

info:
  name: ${spring.application.name}
  hostname: ${eureka.instance.hostname}
  port: ${server.port}
  versions:
    spring-cloud: 2021.0.5
    spring-boot: 2.7.7
    cloud-boot-version: https://start.spring.io/actuator/info
    tomcat: 9.0.70
    Jersey: "1.19.4 05/24/2017 03:20 PM"